// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using EFPowerTools.Models;

namespace EFPowerTools.Models
{
    public partial class MyDBContext
    {

        [DbFunction("fn_GetCadastralFullNo", "dbo")]
        public static string fn_GetCadastralFullNo(Guid? CadastralId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_GetUpdaterInfo", "dbo")]
        public static string fn_GetUpdaterInfo(Guid? userId)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
