// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class ApplicationUserConfiguration : IEntityTypeConfiguration<ApplicationUser>
    {
        public void Configure(EntityTypeBuilder<ApplicationUser> entity)
        {
            entity.ToTable("ApplicationUser", tb => tb.HasComment("使用者"));

            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.UnitId, "IX_ApplicationUser_UnitId");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreateTime).HasComment("建立時間");
            entity.Property(e => e.CreateUserId).HasComment("建立人Id");
            entity.Property(e => e.DisabledTime).HasComment("停用時間");
            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.IsDefault).HasComment("是否為系統預設");
            entity.Property(e => e.IsEnabled).HasComment("是否啟用");
            entity.Property(e => e.IsTemporaryPassword).HasComment("是否為臨時密碼");
            entity.Property(e => e.JobTitle)
                .HasMaxLength(20)
                .HasComment("職稱");
            entity.Property(e => e.LastLoginTime).HasComment("最後登入時間");
            entity.Property(e => e.Name)
                .HasMaxLength(20)
                .HasComment("姓名");
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.PasswordExpiryTime).HasComment("密碼過期時間");
            entity.Property(e => e.Remark)
                .HasMaxLength(200)
                .HasComment("備註");
            entity.Property(e => e.UnitId).HasComment("單位Id(FK Unit.UnitId)");
            entity.Property(e => e.UpdateTime).HasComment("修改時間");
            entity.Property(e => e.UpdateUserId).HasComment("修改人Id");
            entity.Property(e => e.UserName).HasMaxLength(256);
            entity.Property(e => e.UserType).HasComment("帳號類型");

            entity.HasOne(d => d.Unit).WithMany(p => p.ApplicationUsers).HasForeignKey(d => d.UnitId);


            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationUser> entity);
    }
}
