// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class ApplicationUserClaimConfiguration : IEntityTypeConfiguration<ApplicationUserClaim>
    {
        public void Configure(EntityTypeBuilder<ApplicationUserClaim> entity)
        {
            entity.ToTable("ApplicationUserClaim");

            entity.HasIndex(e => e.UserId, "IX_ApplicationUserClaim_UserId");

            entity.HasOne(d => d.User).WithMany(p => p.ApplicationUserClaims)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationUserClaim> entity);
    }
}
