// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class ApplicationRoleClaimConfiguration : IEntityTypeConfiguration<ApplicationRoleClaim>
    {
        public void Configure(EntityTypeBuilder<ApplicationRoleClaim> entity)
        {
            entity.ToTable("ApplicationRoleClaim");

            entity.HasIndex(e => e.RoleId, "IX_ApplicationRoleClaim_RoleId");

            entity.HasOne(d => d.Role).WithMany(p => p.ApplicationRoleClaims)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationRoleClaim> entity);
    }
}
