// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class ApplicationRoleConfiguration : IEntityTypeConfiguration<ApplicationRole>
    {
        public void Configure(EntityTypeBuilder<ApplicationRole> entity)
        {
            entity.ToTable("ApplicationRole", tb => tb.HasComment("角色"));

            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreateTime).HasComment("建立時間");
            entity.Property(e => e.CreateUserId).HasComment("建立人Id");
            entity.Property(e => e.DeleteUserId).HasComment("刪除人Id");
            entity.Property(e => e.DeletedTime).HasComment("刪除時間");
            entity.Property(e => e.HomePageType).HasComment("個人首頁區塊");
            entity.Property(e => e.IsDefault).HasComment("是否為系統預設");
            entity.Property(e => e.IsDeleted).HasComment("是否刪除");
            entity.Property(e => e.IsEnabled).HasComment("是否啟用");
            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
            entity.Property(e => e.Remark)
                .HasMaxLength(200)
                .HasComment("備註");
            entity.Property(e => e.UpdateTime).HasComment("修改時間");
            entity.Property(e => e.UpdateUserId).HasComment("修改人Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApplicationRole> entity);
    }
}
