// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class LogConfiguration : IEntityTypeConfiguration<Log>
    {
        public void Configure(EntityTypeBuilder<Log> entity)
        {
            entity.ToTable("Log", tb => tb.HasComment("Log"));

            entity.Property(e => e.LogId).ValueGeneratedNever();
            entity.Property(e => e.HttpMethod)
                .HasMaxLength(20)
                .HasComment("Http方法");
            entity.Property(e => e.HttpStatusCode)
                .HasMaxLength(20)
                .HasComment("Http狀態碼");
            entity.Property(e => e.Ip)
                .HasMaxLength(45)
                .HasComment("IP位置")
                .HasColumnName("IP");
            entity.Property(e => e.LogLevel)
                .HasMaxLength(50)
                .HasComment("Log層級");
            entity.Property(e => e.LogTime).HasComment("Log時間");
            entity.Property(e => e.Logger)
                .HasMaxLength(250)
                .HasComment("Log來源名稱");
            entity.Property(e => e.Message).HasComment("Log內容");
            entity.Property(e => e.Parameters).HasComment("參數");
            entity.Property(e => e.Path).HasComment("Request路徑");
            entity.Property(e => e.RequestBody).HasComment("Request Body內容");
            entity.Property(e => e.RequestForm).HasComment("Request Form內容");
            entity.Property(e => e.UserId).HasComment("使用者Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Log> entity);
    }
}
