// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class PlayerConfiguration : IEntityTypeConfiguration<Player>
    {
        public void Configure(EntityTypeBuilder<Player> entity)
        {
            entity.ToTable("Player", tb => tb.HasComment("玩家資料"));

            entity.Property(e => e.PlayerId)
                .HasMaxLength(50)
                .HasComment("玩家UID");
            entity.Property(e => e.AircraftPower)
                .HasComment("飛機戰力")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TankPower2")
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasComment("建立時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_CreateTime");
            entity.Property(e => e.CreateUserId)
                .HasDefaultValueSql("(newid())")
                .HasComment("建立人Id")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_CreateUserId");
            entity.Property(e => e.HasT10)
                .HasComment("T10 軍隊")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_MissilePower1");
            entity.Property(e => e.HeadquartersLv)
                .HasComment("總部等級")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TankPower1_1")
                .HasColumnName("HeadquartersLV");
            entity.Property(e => e.MissilePower)
                .HasComment("導彈戰力")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TankPower1")
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasComment("玩家名稱");
            entity.Property(e => e.TankPower)
                .HasComment("坦克戰力")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TankPower")
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.TechDefenseFortifications)
                .HasComment("防禦工作")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TechSpecialForces3");
            entity.Property(e => e.TechHero)
                .HasComment("英雄")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TechSpecialForces1");
            entity.Property(e => e.TechSiegeToSeize)
                .HasComment("攻城拔寨")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_TechSpecialForces2");
            entity.Property(e => e.TechSpecialForces)
                .HasComment("特種部隊")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_HeadquartersLV1");
            entity.Property(e => e.UpdateTime)
                .HasDefaultValueSql("(getdate())")
                .HasComment("修改時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_UpdateTime");
            entity.Property(e => e.UpdateUserId)
                .HasDefaultValueSql("(newid())")
                .HasComment("修改人Id")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Player_UpdateUserId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Player> entity);
    }
}
