// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFPowerTools.Models;
using EFPowerTools.Models.dbo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Security.Claims;

#nullable disable

namespace EFPowerTools.Models.Configurations
{
    public partial class PlayerSnapshotConfiguration : IEntityTypeConfiguration<PlayerSnapshot>
    {
        public void Configure(EntityTypeBuilder<PlayerSnapshot> entity)
        {
            entity.HasKey(e => e.PlayerSnapshot1);

            entity.ToTable("PlayerSnapshot", tb => tb.HasComment("玩家資料快照"));

            entity.Property(e => e.PlayerSnapshot1)
                .HasDefaultValueSql("(newid())")
                .HasComment("玩家快照ID")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_PlayerSnapshot")
                .HasColumnName("PlayerSnapshot");
            entity.Property(e => e.AircraftPower)
                .HasComment("飛機戰力")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_AircraftPower")
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasComment("建立時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_CreateTime");
            entity.Property(e => e.CreateUserId)
                .HasDefaultValueSql("(newid())")
                .HasComment("建立人Id")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_CreateUserId");
            entity.Property(e => e.HasT10)
                .HasComment("T10 軍隊")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_HasT10");
            entity.Property(e => e.HeadquartersLv)
                .HasComment("總部等級")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_HeadquartersLV")
                .HasColumnName("HeadquartersLV");
            entity.Property(e => e.MissilePower)
                .HasComment("導彈戰力")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_MissilePower")
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasComment("玩家名稱");
            entity.Property(e => e.PlayerId)
                .HasMaxLength(50)
                .HasComment("玩家UID");
            entity.Property(e => e.TankPower)
                .HasComment("坦克戰力")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_TankPower")
                .HasColumnType("decimal(6, 2)");
            entity.Property(e => e.TechDefenseFortifications)
                .HasComment("防禦工作")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_TechDefenseFortifications");
            entity.Property(e => e.TechHero)
                .HasComment("英雄")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_TechHero");
            entity.Property(e => e.TechSiegeToSeize)
                .HasComment("攻城拔寨")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_TechSiegeToSeize");
            entity.Property(e => e.TechSpecialForces)
                .HasComment("特種部隊")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_TechSpecialForces");
            entity.Property(e => e.UpdateTime)
                .HasDefaultValueSql("(getdate())")
                .HasComment("修改時間")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_UpdateTime");
            entity.Property(e => e.UpdateUserId)
                .HasDefaultValueSql("(newid())")
                .HasComment("修改人Id")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PlayerSnapshot_UpdateUserId");

            entity.HasOne(d => d.Player).WithMany(p => p.PlayerSnapshots)
                .HasForeignKey(d => d.PlayerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PlayerSnapshot_Player");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PlayerSnapshot> entity);
    }
}
